"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { use, useEffect, useState } from "react";

export default function ProductDetails({ params }) {
  const { id } = use(params);
  const [product, setProduct] = useState(null);
  const [loading, setLoading] = useState(true);
  const [quantity, setQuantity] = useState(1);
  const [form, setForm] = useState({ customer_name: "", customer_email: "", customer_phone: "", shipping_address: "" });
  const [status, setStatus] = useState("");
  useEffect(() => { fetch("/api/products").then((response) => response.ok ? response.json() : []).then((items) => setProduct(items.find((item) => String(item.id) === String(id)) || null)).catch(() => setProduct(null)).finally(() => setLoading(false)); }, [id]);
  const placeOrder = async (event) => { event.preventDefault(); if (!product) return; const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, product_id: product.id, quantity }) }); setStatus(response.ok ? "Order placed successfully" : "Could not place order"); };
  if (loading) return <main className="grid min-h-screen place-items-center bg-stone-50 text-slate-600">Loading product...</main>;
  if (!product) return <main className="min-h-screen bg-stone-50 px-5 py-10"><a href="/" className="text-sm text-lime-700">← Back to store</a><h1 className="mt-14 font-serif text-5xl">Product not found</h1></main>;
  return <main className="min-h-screen bg-stone-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="font-bold">Mobi<span className="text-lime-700">Kiosk</span></a><a href="/" className="text-sm text-slate-500">← Back to store</a></div></header><section className="mx-auto grid max-w-6xl gap-10 px-5 py-12 lg:grid-cols-2 lg:py-20"><div className="grid aspect-square place-items-center overflow-hidden rounded-xl bg-slate-100">{product.image_url ? <img src={product.image_url} alt={product.title} className="h-full w-full object-contain p-8" /> : <span className="font-serif text-8xl text-slate-400">{product.title.slice(0, 1)}</span>}</div><div><p className="text-xs font-bold uppercase tracking-[.25em] text-lime-700">{product.category || "Mobile phone"}</p><h1 className="mt-3 font-serif text-5xl leading-tight md:text-6xl">{product.title}</h1><p className="mt-5 font-serif text-3xl">${Number(product.price).toLocaleString()}</p><p className="mt-4 text-sm leading-7 text-slate-600">Premium device, carefully selected for everyday life. Ships fast from MobiKiosk.</p><p className="mt-4 text-sm font-semibold text-lime-700">{product.stock} units available</p><form onSubmit={placeOrder} className="mt-8 grid gap-3 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl">Place your order</h2><label className="text-xs text-slate-500">Quantity<input required type="number" min="1" max={product.stock} value={quantity} onChange={(event) => setQuantity(Math.min(product.stock, Math.max(1, Number(event.target.value))))} className="mt-1 w-full rounded border border-slate-300 p-3 text-sm" /></label><input required placeholder="Full name" value={form.customer_name} onChange={(e) => setForm({ ...form, customer_name: e.target.value })} className="rounded border border-slate-300 p-3 text-sm" /><input required type="email" placeholder="Email" value={form.customer_email} onChange={(e) => setForm({ ...form, customer_email: e.target.value })} className="rounded border border-slate-300 p-3 text-sm" /><input required placeholder="Phone" value={form.customer_phone} onChange={(e) => setForm({ ...form, customer_phone: e.target.value })} className="rounded border border-slate-300 p-3 text-sm" /><textarea required placeholder="Shipping address" value={form.shipping_address} onChange={(e) => setForm({ ...form, shipping_address: e.target.value })} className="min-h-24 rounded border border-slate-300 p-3 text-sm" /><button className="bg-slate-900 p-3 text-sm font-bold text-white">Place order · ${Number(product.price * quantity).toLocaleString()}</button>{status && <p className="text-sm text-lime-700">{status}</p>}</form></div></section></main>;
}
